version: '3.8'

services:
  munkiwebadmin:
    image: stevekueng/munkiwebadmin
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=munkiwebadmin_db
      - DB_USER=munkiwebadmin_user
      - DB_PASSWORD=munkiwebadmin_pass
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=secret
      - DJANGO_DEBUG=0
      - APPNAME=MunkiWebAdmin
      - TIME_ZONE='Europe/Zurich'
    depends_on:
      - db
      - munki_repo
    links:
      - db
    volumes:
      - munki_repo:/munkirepo
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=munkiwebadmin_user
      - POSTGRES_PASSWORD=munkiwebadmin_pass
      - POSTGRES_DB=munkiwebadmin_db
  munki_repo:
    image: stevekueng/munki-docker
    volumes:
      - munki_repo:/munki_repo
    ports:
      - 8080:80

volumes:
  postgres_data:
  munki_repo: