version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=munkiwebadmin_user
      - POSTGRES_PASSWORD=munkiwebadmin_pass
      - POSTGRES_DB=munkiwebadmin_db

volumes:
  postgres_data: