version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - DEBUG=True
    volumes:
      - .:/munkiwebadmin
      - /Users/Shared/munkirepo:/munkirepo
    ports:
      - "8000:8000"
    depends_on:
      - db
