version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/certs:/etc/nginx/certs
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - VIRTUAL_HOST=kamino.ikueng.ch
    volumes:
      - .:/munkiwebadmin
      - /tmp/munkirepo:/munkirepo
    depends_on:
      - db

volumes:
  Reposado:
    external: false
