#!/bin/bash
source "`dirname "${0}"`/../munkiwebadmin-config"
REPORTSUBMITURL="${MWA_HOST}/api/report"

RUNTYPE="$1"
SERIAL=`ioreg -c IOPlatformExpertDevice | grep IOPlatformSerialNumber | awk '{print $4}' | tr -d '"' | tr -d + | tr -d /`
NAME=`/usr/sbin/scutil --get ComputerName`

curl -H "$authHeader" \
     -H "Content-Type: application/json" \
     -X POST \
     --data "{\"runtype\": \"$RUNTYPE\", \"submission_type\": \"preflight\", \"name\": \"$NAME\"}" \
     $REPORTSUBMITURL/$SERIAL

exit 0
