logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

block_cache:
  block-size-mb: 32
  mem-size-mb: 4096
  prefetch: 80
  parallelism: 128

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: ikueng
  sas: sp=racwdl&st=2024-03-17T16:11:52Z&se=2025-12-01T00:11:52Z&spr=https&sv=2022-11-02&sr=c&sig=DxU4pTADsrethehw6953j7zjL9DnA8Y4op244rcMfPA%3D
  endpoint: https://ikueng.blob.core.windows.net
  mode: sas
  container: munki