#!/usr/local/munki/munki-python

import os
import sys
import subprocess
from mwa2 import utils

sys.path.insert(0, "/usr/local/munki" )
from munkilib import FoundationPlist

def get_hardware_info():
    '''Uses system profiler to get hardware info for this machine'''
    cmd = ['/usr/sbin/system_profiler', 'SPHardwareDataType', '-xml']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, dummy_error) = proc.communicate()
    try:
        plist = FoundationPlist.readPlistFromString(output)
        # system_profiler xml is an array
        sp_dict = plist[0]
        items = sp_dict['_items']
        sp_hardware_dict = items[0]
        return sp_hardware_dict
    except BaseException:
        return {}

def main():
    """ main """
    RUNTYPE = "unknown"
    if len(sys.argv) == 2:
        RUNTYPE = sys.argv[1]

    serialNumber = get_hardware_info()["serial_number"]
    clientName = utils.get_computer_name()
    username = os.getlogin()

    url = "/api/report/"+serialNumber
    data = {"runtype": RUNTYPE, "submission_type": "preflight", "name": clientName, "username": username}
    resc = utils.send_data(url, data)


if __name__ == "__main__":
    main()
