# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='last_inventory_update',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_munki_update',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mac',
        ),
        migrations.AlterField(
            model_name='machine',
            name='os_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ram',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='machine',
            name='remote_ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
